### ISSUE TITLE
help

### ISSUE THREAD

**Issue by rjx678** [rajatguptakgp/image_restoration_techniques#5]
Hello, I had some problems. In dehazing_autoencoder.ipynb,
`mask = np.load('mask.npy',allow_pickle=True)`
where can I find this file?

**Comment by rajatguptakgp** [comment]
Hello, basically I had created numpy array file for the actual images and corresponding masks of the DenseHaze dataset for faster processing. Refer to **dehazing_make_data.py** to create this file. The code originally is for ground-truth images but you can accordingly make changes to get the mask.npy file for yourself. Hope this helps!
